name: CI (a11y)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 12 * * 5'

permissions:
  contents: read

jobs:
  test-a11y-rails:
    name: "a11y tests / Rails ${{ matrix.rails-version }} / Ruby ${{ matrix.ruby-version }}"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/stimulus-plumbers-rails/Gemfile"
    defaults:
      run:
        working-directory: stimulus-plumbers-rails
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.4"
        rails-version:
          - "8.1"
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - run: rm Gemfile.lock

      - uses: browser-actions/setup-chrome@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: latest
          bundler-cache: true

      - run: bundle exec rake test:system
