name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 12 * * 5'

permissions:
  contents: read

jobs:
  test-stimulus:
    name: Stimulus Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: stimulus-plumbers/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: stimulus-plumbers

      - name: Check Format
        run: npm run format:check
        working-directory: stimulus-plumbers

      - name: Lint
        run: npm run lint
        working-directory: stimulus-plumbers

      - name: Test
        run: npm run test
        working-directory: stimulus-plumbers
